/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PlayerBar: typeof import('./src/components/PlayerBar.vue')['default']
    PlayerControl: typeof import('./src/components/playerControl.vue')['default']
    QueueDrawer: typeof import('./src/components/QueueDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongDetail: typeof import('./src/components/songDetail.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

// For TSX support
declare global {
  const ElAvatar: typeof import('element-plus/es')['ElAvatar']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElDrawer: typeof import('element-plus/es')['ElDrawer']
  const ElDropdown: typeof import('element-plus/es')['ElDropdown']
  const ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
  const ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
  const ElEmpty: typeof import('element-plus/es')['ElEmpty']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElPagination: typeof import('element-plus/es')['ElPagination']
  const ElSegmented: typeof import('element-plus/es')['ElSegmented']
  const ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
  const ElTable: typeof import('element-plus/es')['ElTable']
  const ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
  const NavBar: typeof import('./src/components/NavBar.vue')['default']
  const PlayerBar: typeof import('./src/components/PlayerBar.vue')['default']
  const PlayerControl: typeof import('./src/components/playerControl.vue')['default']
  const QueueDrawer: typeof import('./src/components/QueueDrawer.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SongDetail: typeof import('./src/components/songDetail.vue')['default']
}