server:
  port: 3000

spring:
  application:
    name: javaserver

  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:mysql://localhost:3306/musicPlayer?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 061019
    driver-class-name: com.mysql.cj.jdbc.Driver

#   data:
#     redis:
#       host: localhost
#       port: 6379
#       # password: 如果有密码就写

logging:
  level:
    root: info
    "com.kyf.mp.javaserver": debug

jwt:
  secret: 88bada62dd3a3db3f85962a81a916a9a23149491f59387b805024aff42900064
  expire: 86400000

file:
  upload:
    song-path: "Z:/vue3_projects/vue_musicplayer/server/static/songs/"
    song-cover-path: "Z:/vue3_projects/vue_musicplayer/server/static/song_covers/"
    playlist-cover-path: "Z:/vue3_projects/vue_musicplayer/server/static/playlist_covers/"
  static:
    song-url: "http://127.0.0.1/static/songs/"
    song-cover-url: "http://127.0.0.1/static/song_covers/"
    playlist-cover-url: "http://127.0.0.1/static/playlist_covers/"
