sonar.projectKey=musicPlayer
sonar.projectName=musicPlayer
sonar.host.url=http://localhost:9000

sonar.sources=web, backend

sonar.inclusions=**/*.ts, **/*.tsx, **/*.js, **/*.jsx, **/*.vue

sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**, **/public/**, **/*.test.ts, **/*.spec.ts

sonar.sourceEncoding=UTF-8
