sonar.projectKey=musicPlayer
sonar.projectName=musicPlayer
sonar.host.url=http://localhost:9000
sonar.token=squ_6ad6005f987721c1075ab6e33cf97db1d530dc53

sonar.sources=client, server

sonar.inclusions=**/*.ts, **/*.tsx, **/*.js, **/*.jsx, **/*.vue

sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**, **/public/**, **/*.test.ts, **/*.spec.ts

sonar.sourceEncoding=UTF-8
