spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/starter}
    username: ${SPRING_DATASOURCE_USERNAME:starter}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  flyway:
    enabled: true
server:
  servlet:
    context-path: /
app:
  jwt-secret: ${APP_JWT_SECRET:}
