/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSidebar: typeof import('element-plus/es')['ElSidebar']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    LyricsPanel: typeof import('./src/components/song-detail/components/LyricsPanel.vue')['default']
    NavBar: typeof import('./src/components/nav-bar/NavBar.vue')['default']
    PlayerBar: typeof import('./src/components/player-bar/PlayerBar.vue')['default']
    PlayerControl: typeof import('./src/components/player-control/PlayerControl.vue')['default']
    ProgressBar: typeof import('./src/components/player-control/components/ProgressBar.vue')['default']
    QueueDrawer: typeof import('./src/components/queue-drawer/QueueDrawer.vue')['default']
    QueueItem: typeof import('./src/components/queue-drawer/components/QueueItem.vue')['default']
    QueueList: typeof import('./src/components/queue-drawer/components/QueueList.vue')['default']
    QueuePreviewList: typeof import('./src/components/queue-drawer/components/QueuePreviewList.vue')['default']
    RecordDisc: typeof import('./src/components/song-detail/components/RecordDisc.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongDetail: typeof import('./src/components/song-detail/SongDetail.vue')['default']
    SongInfo: typeof import('./src/components/player-bar/components/SongInfo.vue')['default']
    VolumeControl: typeof import('./src/components/player-bar/components/VolumeControl.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

// For TSX support
declare global {
  const ElAside: typeof import('element-plus/es')['ElAside']
  const ElAvatar: typeof import('element-plus/es')['ElAvatar']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCard: typeof import('element-plus/es')['ElCard']
  const ElContainer: typeof import('element-plus/es')['ElContainer']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElDrawer: typeof import('element-plus/es')['ElDrawer']
  const ElDropdown: typeof import('element-plus/es')['ElDropdown']
  const ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
  const ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
  const ElEmpty: typeof import('element-plus/es')['ElEmpty']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElImage: typeof import('element-plus/es')['ElImage']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElMain: typeof import('element-plus/es')['ElMain']
  const ElMenu: typeof import('element-plus/es')['ElMenu']
  const ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
  const ElPagination: typeof import('element-plus/es')['ElPagination']
  const ElProgress: typeof import('element-plus/es')['ElProgress']
  const ElSegmented: typeof import('element-plus/es')['ElSegmented']
  const ElSidebar: typeof import('element-plus/es')['ElSidebar']
  const ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
  const ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
  const ElTable: typeof import('element-plus/es')['ElTable']
  const ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
  const ElUpload: typeof import('element-plus/es')['ElUpload']
  const LyricsPanel: typeof import('./src/components/song-detail/components/LyricsPanel.vue')['default']
  const NavBar: typeof import('./src/components/nav-bar/NavBar.vue')['default']
  const PlayerBar: typeof import('./src/components/player-bar/PlayerBar.vue')['default']
  const PlayerControl: typeof import('./src/components/player-control/PlayerControl.vue')['default']
  const ProgressBar: typeof import('./src/components/player-control/components/ProgressBar.vue')['default']
  const QueueDrawer: typeof import('./src/components/queue-drawer/QueueDrawer.vue')['default']
  const QueueItem: typeof import('./src/components/queue-drawer/components/QueueItem.vue')['default']
  const QueueList: typeof import('./src/components/queue-drawer/components/QueueList.vue')['default']
  const QueuePreviewList: typeof import('./src/components/queue-drawer/components/QueuePreviewList.vue')['default']
  const RecordDisc: typeof import('./src/components/song-detail/components/RecordDisc.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SongDetail: typeof import('./src/components/song-detail/SongDetail.vue')['default']
  const SongInfo: typeof import('./src/components/player-bar/components/SongInfo.vue')['default']
  const VolumeControl: typeof import('./src/components/player-bar/components/VolumeControl.vue')['default']
}